In [2]:
import numpy as np

# Problem Statement:
You work in XYZ Corporation as a Data Analyst. Your corporation has told you to
work with the structure of the data.
# Tasks To Be Performed:
1. Create a list named ‘myList’ that has the following elements: 10, 20, 30,
‘apple’, True, 8.10:
<br><br>a. Now in the ‘myList’, append these values: 30, 40
<br><br>b. After that, reverse the elements of the ‘myList’ and store that in
‘reversedList’
<br><br>
2. Create a dictionary with key values as 1, 2, 3 and the values as ‘data’,
‘information’ and ‘text’:
<br><br>a. After that, eliminate the ‘text’ value from the dictionary
<br><br>b. Add ‘features’ in the dictionary
<br><br>c. Fetch the ‘data’ element from the dictionary and display it in the output
<br><br>
3. Create a tuple and add these elements 1, 2, 3, apple, mango in my_tuple.
<br><br>
4. Create another tuple named numeric_tuple consisting of only integer
values 10, 20, 30, 40, 50:
<br><br>a. Find the minimum value from the numeric_tuple
<br><br>b. Concatenate my_tuple with numeric_tuple and store the result in r1
<br><br>c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’
<br><br>
5. Create 2 sets with the names set1 and set2, where set1 contains
{1,2,3,4,5} and set2 contains {2,3,7,6,1}
<br><br>Perform the below operation:
<br>a. set1 union set2
<br>b. set1 intersection set2
<br>c. set1 difference set2


In [4]:
# 1
my_list = [10,20,30,'apple',True,8,10]

my_list.append(30)# a
my_list.append(40)

reversed_list = my_list[::-1]# b
reversed_list

[40, 30, 10, 8, True, 'apple', 30, 20, 10]

In [16]:
# 2
my_dict = {1:"data",
           2:"information",
           3:"text"}

my_dict.pop(3)# a
print(my_dict)

my_dict[4] = "features"# b
print(my_dict)

print(my_dict.get(1))# c

{1: 'data', 2: 'information'}
{1: 'data', 2: 'information', 4: 'features'}
data


In [24]:
# 3
my_tuple = ()

my_tuple += (1,2,3,'apple','mango')
print(my_tuple)

# 4
numeric_tuple = (10,20,30,40,50)
print(min(numeric_tuple))# a

r1 = my_tuple + numeric_tuple# b
print(r1)

newdupli = my_tuple*2 # c
print(newdupli)

(1, 2, 3, 'apple', 'mango')
10
(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)
(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


In [26]:
# 5
set1 = {1,2,3,4,5}
set2 = {2,3,7,6,1}

print(set1.union(set2)) # a
print(set1.intersection(set2)) # b
print(set1.difference(set2)) # c

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3}
{4, 5}


# Problem Statement:
You work in XYZ Corporation as a Data Analyst. Your corporation has told you to
use the NumPy package and do some tasks related to that.
# Tasks To Be Performed:
1. Create a 3x3 matrix array with values ranging from 2 to 10.
<br><br>
2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]
<br><br>
3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]
<br><br>
4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.
<br><br>
5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1
<br><br>
Perform the following tasks:
<br>a. Extract the 1st row from the array
<br>b. Extract the last element from the array

In [30]:
#1
np.arange(2,10+1).reshape((3,3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [36]:
# 2
arr = np.array([1,2,3,4])
arr.astype(dtype=float)

array([1., 2., 3., 4.])

In [45]:
# 3
arr = np.array([10,20,30])
arr = np.append(arr,40)
arr = np.append(arr,50)
arr = np.append(arr,60)
arr = np.append(arr,70)
arr = np.append(arr,80)
arr = np.append(arr,90)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
# 4
arr1 = np.array([1,1,2,3,1])
arr2 = np.array([2,1,7,5,2])

sumArray = np.add(arr1,arr2)
sumArray

array([3, 2, 9, 8, 3])

In [57]:
# 5
array1 = np.arange(10,90+10,10).reshape((3,3))

print(array1[:1,:])# a
print(array1[-1:,-1:])# b

[[10 20 30]]
[[90]]


#Problem Statement:
You work in XYZ Company as a Python developer. The company officials want
you to build a Python program.
#Tasks To Be Performed:
1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
value and returns a NumPy array of the given dimension filled with the
given value e.g.: solve((3, 3), 5) will return
<br>[
<br>[5, 5, 5],
<br>[5, 5, 5],
<br>[5, 5, 5]
<br>]
<br><br>
2. Create a method that takes n NumPy arrays of the same dimensions,
sums them and returns the answer.
<br><br>
3. Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
top-left N X M sub matrix, e.g:
<br>[
<br>[1, 2, 3],
<br>[4, 5, 6],
<br>[7, 8, 9],
<br>]
<br>top_left_sub_matrix (matrix, 2, 2) -> should return:
<br>[
<br>[1, 2]
<br>[4, 5]
<br>]
<br><br>
4. Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
bottom-right N X M sub matrix, e.g:
<br>[
<br>[1, 2, 3],
<br>[4, 5, 6],
<br>[7, 8, 9],
<br>]
<br>sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are
zero indexed)
<br>[
<br>[5, 6]
<br>[8, 9]
<br>]
<br><br>
5. Given a 1 D NumPy Array. Write a function that accepts this array as
parameters. The method should return a dictionary with 'mean' and
'std_dev' as key and array's mean and array's standard deviation as
values:
<br>[1, 1, 1]
<br>solution(arr) -> should return :
<br>{'mean': 1.0, 'std_dev': 0.0}

In [6]:
# 1
def solve(dims, num):
  return np.full(dims,num)

solve((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [8]:
# 2
def addition(arr_list):
  sums = np.empty(arr_list[0].shape)
  for i in arr_list:
    sums = np.add(sums, i)
  return sums.astype(dtype=int)

arr1 = np.array([[1,2,3],[2,1,4],[1,1,1]])
arr2 = np.array([[2,2,3],[1,2,6],[2,1,2]])
addition([arr1,arr2])

array([[ 6,  8, 12],
       [ 6,  6, 20],
       [ 6,  4,  6]])

In [19]:
# 3
def top_sub_matrix(matrix,m,n):
  return matrix[:m,:n]

arr = np.array([[1,2,4],[2,1,3],[1,3,1]])
top_sub_matrix(arr,2,2)

array([[1, 2],
       [2, 1]])

In [20]:
# 4
def bot_sub_matrix(matrix,m,n):
  return matrix[m:,n:]

arr = np.array([[1,2,4],[2,1,3],[1,3,1]])
bot_sub_matrix(arr,1,1)

array([[1, 3],
       [3, 1]])

In [22]:
# 5
def describe(arr):
  return {"mean":np.mean(arr), "std_dev":np.std(arr)}


arr = np.array([1,2,1,5,2,5,2,4])
describe(arr)

{'mean': 2.75, 'std_dev': 1.5612494995995996}